apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi
          image: kundanpandey15/climateapi:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: mongo-config
          env:
            - name: ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-config
                    key: ConnectionString

---

apiVersion: v1
kind: Service
metadata:
  name: webapi-service
spec:
  type: LoadBalancer
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
