apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MONGO_HOST: mongo-service
  MONGO_PORT: "27017"
  appsettings.json: |
    {
        "Logging": {
            "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
            }
        },
        "AllowedHosts": "*",
        "ConnectionStrings": {
            "MongoDB": "mongodb://mongo-service:27017"
        },
        "MongoDB": {
            "DatabaseName": "WeatherForecast"
        }
    }